### ISSUE TITLE
Incorrectly applied to CSS Selectors & comments

### ISSUE THREAD

**Issue by Mottie** [easylogic/codemirror-colorpicker#13]
In css mode, the color picker is being applied to named css selectors:

![](https://user-images.githubusercontent.com/136959/29590439-70527f98-875f-11e7-8c9c-9df33b5b5a31.png)

and inside of comments:

![](https://user-images.githubusercontent.com/136959/29590548-fce32a3e-875f-11e7-9b38-0977ad376144.png)

**Comment by easylogic** [comment]
hi @Mottie 

This is a bug. I will fix the bug as soon as possible.

**Comment by easylogic** [comment]
@Mottie 

I released v1.0.9 for this issue. 

please test for color.
