### ISSUE TITLE
Too slow when paste a long text

### ISSUE THREAD

**Issue by sylingd** [easylogic/codemirror-colorpicker#14]
For example, there are tow pages, 1.html has colorpicker plugin and 2.html not
[1.html](https://ext.firefoxcn.net/demo/1.html)
[2.html](https://ext.firefoxcn.net/demo/2.html)

If paste a long text (more than 30000, for example, [this file](https://ext.firefoxcn.net/demo/test.css) ), the 1.html will be "no response" in about 10 seconds. I use "Performance" tool in Chrome's devtools, it shows that most of the time is spent on "Layout"
![2017-11-20_235849](https://user-images.githubusercontent.com/5326684/33027688-c69b7298-ce4e-11e7-925d-57c7bf318038.png)

If in a complex web page, the situation is more serious.

Here is [Google's document](https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing#avoid-forced-synchronous-layouts)

You can load [my performance profile](https://github.com/easylogic/codemirror-colorpicker/files/1488249/Profile.zip)
![2017-11-21_000050](https://user-images.githubusercontent.com/5326684/33027842-304467d6-ce4f-11e7-8a1d-53f105dc55dd.png)

(I did not delve into it, but maybe asynchronous initialization can solve the problem?)

**Comment by easylogic** [comment]
hi @sylingd  

Thanks for your report.

I will check it .

**Comment by easylogic** [comment]
i fixed this issue.  

please test it in v1.0.10

**Comment by sylingd** [comment]
It works well, thank you
