### ISSUE TITLE
hideDelay cannot be set to 0 when used with CodeMirror

### ISSUE THREAD

**Issue by fxOne** [easylogic/codemirror-colorpicker#17]
**Describe the bug**
The color picker is closed after 2sec if the hideDelay ist set to 0.

**To Reproduce**

```
var cm = CodeMirror.fromTextArea(document.getElementById("sample_text_area"), {
    colorpicker : {
        mode : 'edit',
        hideDelay: 0
    }
});
```

The issue can be found [here](https://github.com/easylogic/codemirror-colorpicker/blob/master/src/colorview/index.js#L213) as in `hideDelay: self.opt.hideDelay || 2000` hideDelay will be falsy if it is set to 0.

**Expected behavior**
The color picker should stay open with the hideDelay set to 0.

**Comment by easylogic** [comment]
@fxOne  

Thanks for your report. 

I'll fix it and let you know.
