### ISSUE TITLE
HSL / HSLA as default color is not working

### ISSUE THREAD

**Issue by hcomnetworkers** [easylogic/codemirror-colorpicker#18]
**Describe the bug**
When giving a HSL or HSLA string for the color picker it is not correctly parsed.

**To Reproduce**
See the codepen: https://codepen.io/anon/pen/dqVvLG

**Expected behavior**
The HSL or HSLA string input should work.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 68

**Comment by easylogic** [comment]
@hcomnetworkers  

Thanks for your report. 

This is a bug. 

I will fix this issue.

**Comment by easylogic** [comment]
@hcomnetworkers  

it is fixed.  

please refer to  v1.9.21
