### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by mikhoul** [easylogic/codemirror-colorpicker#2]
Hi, 

I was looking for a color picker addon for Codemirror with support for Alpha channel too and I your colorpicker.

I was using previously https://github.com/enjalot/Inlet but it don't support Alpha channel transparency.

**The bug:**  I was trying your demo at https://store.jui.io/v2/view.php?id=58930a1a94976c9b562541a6
and I pasted this LESS/CSS code inside to see what will happen:

```
// The main font color controls the color of the text and the icons (font icons)
@main-font-color: #CCCCCC; // e.g. rgb(255, 255, 255) or #ffffff

// The default color of control backgrounds is mostly black but with a little
// bit of blue so it can still be seen on all black video frames, which are
// common.
@control-bg-color: #07141E; // e.g. rgb(255, 255, 255) or #ffffff
@control-bg-alpha: 0.7; // 1.0 = 100% opacity, 0.0 = 0% opacity

// The slider bar color is used for the progress bar and the volume bar
@slider-bar-color: #66A8CC; // e.g. rgb(255, 255, 255) or #ffffff
// The background of the progress bar and volume bar have a lined pattern that
// is created from a base64 encoded image. You can generate your own pattern at
// http://www.patternify.com/ then replace the value in the quotes with your own
@slider-bar-pattern: ~'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAYAAAAGCAYAAADgzO9IAAAAP0lEQVQIHWWMAQoAIAgDR/QJ/Ub//04+w7ZICBwcOg5FZi5iBB82AGzixEglJrd4TVK5XUJpskSTEvpdFzX9AB2pGziSQcvAAAAAAElFTkSuQmCC';
// The color of the slider background
@slider-background-color: #333333;
@slider-background-alpha: 0.9; // 1.0 = 100% opacity, 0.0 = 0% opacity
```
The problem is that when I paste the code inside the editor the "code" is **NOT** processed so there is no swatch beside the color to edit them.

But if I put my cursor near a color code and I enter a space it will be parsed for this line and add the color swatch.

Sometime it did not work when I was editing/writing by hand the color code pasted.

**Here's a Screencast to show you the bug** since english is not my first language and look carefully at the last 25 seconds it will show that even when I input the color code "by hand" with the keyboard inside the  pasted code it did not work,

SCREENCAST:  http://screencast-o-matic.com/watch/cbeqFi6pgD

Best Regards :octocat:

**Comment by easylogic** [comment]
@mikhoul  

Thanks for your reporting. 

paste is not yet implements.

 I'll implement it soon and let you know.

**Comment by easylogic** [comment]
@mikhoul 

1.0.4 version is released for support paste event.

Use npm or bower.

**Comment by easylogic** [comment]
update sample : https://store.jui.io/v2/view.php?id=58930a1a94976c9b562541a6
