### ISSUE TITLE
hideDelay does not work as expected

### ISSUE THREAD

**Issue by hcomnetworkers** [easylogic/codemirror-colorpicker#20]
**Describe the bug**
As stated in the API reference:

> // default value is 2000.  color picker don't hide automatically when hideDelay is zero

With the fix for #17 the value `0` does now hide instantly.

**Expected behavior**
We want to have an option to display the show the color picker until a user action followed to hide it, like clicking on the overlay. Consider allow `Infinity` to be passed to the `hideDelay` option.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 68

**Comment by easylogic** [comment]
@hcomnetworkers  

i fixed it.  

Please refer to v1.9.22

**Comment by hcomnetworkers** [comment]
Thanks for the quick fixes and feature integrations, thats awesome.
