### ISSUE TITLE
Update palette on existing instance

### ISSUE THREAD

**Issue by hcomnetworkers** [easylogic/codemirror-colorpicker#21]
**Is your feature request related to a problem? Please describe.**
As described in #19 we are using redux to allow color selections. We have specific collections of color sets that we are using as palette. Currently there is no option in the API reference that would allow a change of the palette within an exisitng instance, as our redux state could constantly change, the palette would be outdated.

**Describe the solution you'd like**
A public method that allows to update the color palette. 
I actually tried this:
https://github.com/easylogic/codemirror-colorpicker/blob/master/src/colorpicker/BaseColorPicker.js#L288-L290
But it did not appear to work as expected.

**Comment by easylogic** [comment]
@hcomnetworkers  

It has no feature for updating palette. 

I think I need to add this function separately.

**Comment by easylogic** [comment]
please refer to https://easylogic.github.io/codemirror-colorpicker/1/api.html#callback-for-show-and-hide. 

i released v1.9.22

**Comment by hcomnetworkers** [comment]
I am sorry, we might had a small miss communication / bad speech in that issue.

I want to replace the whole color palettes of a color picker. 
Not only the colors of the current active one.

**Comment by easylogic** [comment]
@hcomnetworkers  

ok, I understood. 

I will implement and talk to you.

**Comment by easylogic** [comment]
@hcomnetworkers 

I fixed this issue and released v1.9.31 

Please refer to https://easylogic.github.io/codemirror-colorpicker/1/api.html#set-all-colors-in-whole-palette
