### ISSUE TITLE
Colorpicker is running out of the screen

### ISSUE THREAD

**Issue by fxOne** [easylogic/codemirror-colorpicker#25]
**Describe the bug**
The color picker is outside of the screen and not fully visible on the first click. On the 2nd click the color picker is aligned correctly

**To Reproduce**
1. Go to https://codepen.io/anon/pen/xyLKvN
2. Click on in the first line on the green color field
3. Colorpicker is partly out of screen
4. Click 2nd time on the green color field
5. Colorpicker is now correct aligned

**Expected behavior**
Colorpicker should have have the correct alignment on the first click.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 69

**Comment by easylogic** [comment]
hi @fxOne  

I will check this issue.

**Comment by easylogic** [comment]
i released v1.9.36 

please test it.

**Comment by fxOne** [comment]
Works perfect for me 👍
