### ISSUE TITLE
Codemirror triggers only one blur event

### ISSUE THREAD

**Issue by fxOne** [easylogic/codemirror-colorpicker#26]
**Describe the bug**
Only the first selection inside of the colorpicker triggers a blur event. Further changes does not trigger the event. As i have the save method bound to the blur event i get not further change notifications

**To Reproduce**
1. Go to https://codepen.io/anon/pen/xyLKvN
2. Open the colorpicker by clicking on a color
3. Change the color without closing the color picker
4. the blur event is triggert with the new color
5. Change the color again to a differnt color
6. no blur event is triggert
7. wait until the color picker closes or click outside of the codemirror area

**Expected behavior**
Colorpicker should trigger the blur event on codemirror to notify for changes or put the cursor back to the old position after auto closing.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 69

**Comment by easylogic** [comment]
@fxOne  

i am checking it.

**Comment by easylogic** [comment]
i released v1.9.36 

please test it.

**Comment by easylogic** [comment]
The codemirror blur event seems to be twisted. I'll test the event logic again.

**Comment by easylogic** [comment]
please test  v1.9.37.

it apply hide delay time(default 1s) to colorpicker when codemirror is blur

**Comment by fxOne** [comment]
Now it behaves like the pre v1.9.36: https://codepen.io/anon/pen/xyLKvN
The blur event is only triggered for the first color change

**Comment by easylogic** [comment]
@fxOne  

i rebuild v1.9.39 

please use  this 

`https://cdn.jsdelivr.net/npm/codemirror-colorpicker@1.9.39/dist/codemirror-colorpicker.min.js `

**Comment by fxOne** [comment]
No, does not work, now I have the behavior that the colorpicker closes after a few seconds after the mouse down and I can still change the color by moving the mouse as in v1.9.36

**Comment by easylogic** [comment]
hmm 

sorry.
