### ISSUE TITLE
es6 import error  in webpack4.0

### ISSUE THREAD

**Issue by chenweibo** [easylogic/codemirror-colorpicker#29]
Failed to compile.

./node_modules/_codemirror-colorpicker@1.9.46@codemirror-colorpicker/dist/codemirror-colorpicker.js
Module not found: Error: Can't resolve 'codemirror' in '/project/qcode/node_modules/_codemirror-colorpicker@1.9.46@codemirror-colorpicker/dist'

**Comment by easylogic** [comment]
hi @chenweibo  

Thanks for your report.

I'll check it.

**Comment by easylogic** [comment]
@chenweibo  

I released v1.9.47. 

Please test it.
