### ISSUE TITLE
Small bug.

### ISSUE THREAD

**Issue by mikhoul** [easylogic/codemirror-colorpicker#3]
When "transparent" is set as a color it is not recognized as a "color".

Screenshot: http://i.imgur.com/wQGTXiA.png 

Regards :octocat:

**Comment by mikhoul** [comment]
Oups !  Same thing for other colors that are non numerical like "gray" or "red" etc...

Regards :octocat:

**Comment by easylogic** [comment]
@mikhoul 

color name is not yet support. 

color name will add in next release.

**Comment by mikhoul** [comment]
Thanks !

Le mercredi 5 avril 2017, jinho park <notifications@github.com> a écrit :
> @mikhoul
>
> color name is not yet support.
>
> color name will add in next release.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/F-cG-iLe08IUebj44Ri9KDikF65qDcVb9Bz9wHq4Z9ty3V9kmvSeTNi2g5xNGN_69rJ23-YjVUs7GwXYefQ3o8GoglFqH5L4UCUD8wRJ5DwVkpoiWCNyr8RaqJdryzd9Tg209_VTBM7yX9wxUGlJ7nQSWgsVbQ=s0-d-e1-ft#https://github.com/notifications/beacon/AFamUeiKpXvfW46CeFZsxbK7oCnNDDr-ks5rsyr6gaJpZM4Mv8rj.gif>

**Comment by easylogic** [comment]
please test in v1.0.5.

color name is now supported.
