### ISSUE TITLE
Invalid colors are also highlighted

### ISSUE THREAD

**Issue by webextensions** [easylogic/codemirror-colorpicker#31]
**Describe the bug**
Even if you type invalid color code, it would still highlight it as a color in CodeMirror.
For example: Type "#000a" and it would show up as black color.

**To Reproduce**
1. Go to https://colorpicker.easylogic.studio/#codemirror-colorpicker-addon
2. Click on the editor inside "CodeMirror ColorPicker Addon"
3. Type "#000a" (without quotes)
4. It would show up as a color

**Expected behavior**
Invalid hex codes should not be identified as colors.

**Screenshots**
This is the screenshot for my browser extension where I face the same issue:
https://user-images.githubusercontent.com/29383712/51375676-d0e60500-1b06-11e9-83b2-701de05752ac.png
Reference: https://github.com/webextensions/live-css-editor/issues/23#issue-400628007

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: 1.9.49

**Smartphone (please complete the following information):**
 - Device: Not tested
 - OS: Not tested
 - Browser: Not tested
 - Version: Not tested

**Additional context**
I would recommend that if a hex code (or valid color) is immediately followed by a whitespace / single-quote / double-quote character / etc, then only it should be considered as a valid color. Otherwise, treat it as an invalid color and don't highlight it.

**Comment by easylogic** [comment]
thank you for reporting, @webextensions  

I checked it.  

I'll let you know when it's fixed.

**Comment by easylogic** [comment]
@webextensions   

I have some problem.  

CodeMirror's token is not exactly. 

For example,   

```css
#d34-background {
    blue: blue; 
}
```

#d34 and first blue  are  that token is null. 

The problem is that last blue's toke type is also null.

So  it will take some time for this to be resolved.

**Comment by easylogic** [comment]
@webextensions  

I released v1.9.50 

please test it.
