### ISSUE TITLE
Can I get different events between mouseup and mousedown?

### ISSUE THREAD

**Issue by lqez** [easylogic/codemirror-colorpicker#35]
Colorpicker only has one callback for selecting colors. I need to distinguish `mouseup` and `mousedown` events.

While dragging the picker – this means “I'm choosing a color, not finished.”
When I picked a color from the palette or released the picker – this means “I'm finished to choose.”

I'm building a web-based content editor and I would like to push an undo history only when a user has finished choosing a color. Currently, tons of history had been pushed while choosing a color :(

**Comment by easylogic** [comment]
hi @lqez  

ok, I am understand.

**Comment by easylogic** [comment]
When  onLastUpdate is fire 

* [ ] change color saturation   
* [ ] change hue bar  
* [ ] change opacity
* [ ] change Input color text  
* [ ] click predefined color

**Comment by easylogic** [comment]
@lqez  

i released  codemirror-colorpicker v1.9.53  and @easylogic/colorpicker v1.9.65.  

Please check it.

**Comment by lqez** [comment]
Awesome!

**Comment by easylogic** [comment]
refer to https://colorpicker.easylogic.studio/colorpicker/api.html#callback-for-change-and-hide
