### ISSUE TITLE
Changing hexcolor with existing alpha value will not replace full hexstring in editor 

### ISSUE THREAD

**Issue by Mooreel** [easylogic/codemirror-colorpicker#38]
**Describe the bug**
In case of an existing 8 char hexcolor value in the editor containing the alpha value, changing the alpha value in the colorpicker leads to not fully replacing the hexstring in the editor but inserting it so that in the editor a 10 char invalid hexcolor code appears.

**To Reproduce**
1. Have a 8 char hexcode containing a two char alpha value in the editor
2. click on the color picker square
3. change alpha value
4. leave color picker

**Expected behavior**
Full hexstring in codemirror editor is replaced with string from color picker

**Screenshots**
Editor 8char hex value
![image](https://user-images.githubusercontent.com/1982509/81183920-0ccd0400-8fb0-11ea-99d9-7ff3b8efdb2d.png)

color picker: change alpha value 
![image](https://user-images.githubusercontent.com/1982509/81183952-18b8c600-8fb0-11ea-931c-e4ea291c65d1.png)

now editor has a 10 char hex value
![image](https://user-images.githubusercontent.com/1982509/81183974-1e161080-8fb0-11ea-9541-35fbaac12741.png)

**Desktop (please complete the following information):**
 - Windows
- Chrome version 81.0.4044.129 (Official Build) (64-bit)

**Comment by Mooreel** [comment]
Are issues in this repo looked at? If there is a pointer where this bug might come from I can try fixing it myself.

**Comment by easylogic** [comment]
hi @Mooreel
Sorry to see the issue too late. I'll check the relevant code and tell you again.

**Comment by easylogic** [comment]
I fixed this issue. 

you can use v1.9.70 .  

please test it.

**Comment by Mooreel** [comment]
Thank you very much for the support @easylogic . That indeed fixed it.
