### ISSUE TITLE
color-picker shows next to CSS classes

### ISSUE THREAD

**Issue by hamedbaatour** [easylogic/codemirror-colorpicker#39]
**Describe the bug**
color picker shows next to css class. should only show next to CSS color properties.

**To Reproduce**
1. write any CSS class that includes CSS colors (red, blue, green...) and color picker selector will show up

**Expected behavior**
Should only be shown next to CSS color properties 

**Screenshots**
![image](https://user-images.githubusercontent.com/5658460/88406035-c467fa00-cdd8-11ea-924a-d73fd5d6191c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: All
 - Version latest

**Comment by easylogic** [comment]
hi @hamedbaatour 

Thanks for your reporting. 

I will release new version about this.

**Comment by easylogic** [comment]
I released new version v1.9.71.

Please try to test it
