### ISSUE TITLE
Picker immediately closes after opening

### ISSUE THREAD

**Issue by hamedbaatour** [easylogic/codemirror-colorpicker#40]
**Describe the bug**
picker closes as soon as it is clicked

**To Reproduce**
- load codemirror+codemirror-colorpicker
- remove editor from DOM (v-if/ng-if...)
- reinit codemirror editor (reinsert to DOM)
- try to open codemirror-colorpicker 
- issue happens

**Expected behavior**
picker should stay open

**Screenshots**
picker opens and immediately the 'onchange' handler gets called and closes it.

![ezgif com-resize (1)](https://user-images.githubusercontent.com/5658460/88456059-54627e00-ce83-11ea-9c05-8c59c3af0194.gif)

## Potential Fix / Additional Context

fixed the issue by removing  `cm.state.colorpicker.close_color_picker();` in side the OnChange function

```

function onChange(cm, evt) {
    if (evt.origin == 'setValue') {
       //  cm.state.colorpicker.close_color_picker();  // <========= removed this line
        cm.state.colorpicker.init_color_update();
        cm.state.colorpicker.style_color_update();
    } else {
        cm.state.colorpicker.style_color_update(cm.getCursor().line);
    }
}
```

**Desktop**
 - OS: Windows
 - Browser: all
 - Version: latest 1.9.71

**Comment by easylogic** [comment]
hi @hamedbaatour   

I fixed your issue. 
please try  to  test  it  on v1.9.72

**Comment by hamedbaatour** [comment]
@easylogic thanks for the quick fix. Really appreciate it 👍
