### ISSUE TITLE
Implement Color Dropper to Grab Colors Outside the Picker?

### ISSUE THREAD

**Issue by shermandickman** [easylogic/codemirror-colorpicker#42]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Is it possible to select a color that is outside the picker window? Sometimes it's helpful to grab a starting color from outside the picker.

**Describe alternatives you've considered**
Using Sketch or SIP to grab the color. Currently, the color has to be pasted into the codemirror color picker, which is a bit inefficient.

**Additional context**
<img width="225" alt="Screen Shot 2020-11-22 at 6 30 52 PM" src="https://user-images.githubusercontent.com/7443120/99924981-18d0a700-2cf1-11eb-8dd7-704454e55886.png">

**Comment by easylogic** [comment]
hi @shermandickman 

Thank you for your good opinion.
I also thought about this function a lot.
However, since it is a web environment, it is difficult to come up with a way to set the color correctly differently from the native app.

I think I need some time to do research.

**Comment by easylogic** [comment]
hi @shermandickman  

I released new version with eyedropper.  

please test it with codemirror-colorpicker@1.9.74 

---- 

eyedropper is a browser native feature.  (refer to https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper_API)
