### ISSUE TITLE
color picker shows inside some CSS selectors (example `#address`)

### ISSUE THREAD

**Issue by hamedbaatour** [easylogic/codemirror-colorpicker#44]
**Describe the bug**
color picker appears inside a css selector when wirting `#address` inside a codemiror code editor

**To Reproduce**
- write `#address` css selector and a teal color picker instance will show up

**Expected behavior**
color picker should not show inside any CSS selector ( I saw the same issue with other CSS selectors but I can't remember them exactly)

**Screenshots**
![image](https://user-images.githubusercontent.com/5658460/128598333-48a78fec-555f-4fa8-af6b-b19df4cd04b9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome Version 92.0.4515.131 (Latest)
 - Version ^1.9.72 (Latest)

**Comment by easylogic** [comment]
hi @hamedbaatour  

I will check it.

**Comment by easylogic** [comment]
@hamedbaatour  

 Can you show me  your codemirror version ?

**Comment by hamedbaatour** [comment]
I am using codemirror version `^5.62.0` I will try to reproduce the issue in a codepen and post it later.

**Comment by easylogic** [comment]
Hi @hamedbaatour  

I fixed this issue. 

Please test it  in codemirror-colorpicker v1.9.73.
