### ISSUE TITLE
Problems using with Browserify

### ISSUE THREAD

**Issue by teleclimber** [easylogic/codemirror-colorpicker#5]
If I bundle my browser-side code with browserify I have to change this addon's code to get it to work.

If I do `npm install codemirror-colorpicker` it gets installed in my `node-modules`. (`CodeMirror` is in `node-modules` too.)

Your code tries to load CM as such:

```
(function(mod) {
    if (typeof exports == "object" && typeof module == "object") // CommonJS
        mod(require("../../lib/codemirror"), require("./foldcode"));
    else if (typeof define == "function" && define.amd) // AMD
        define(["../../lib/codemirror", "./foldcode"], mod);
    else // Plain browser env
        mod(CodeMirror);
})(function(CodeMirror) {
...
```

But naturally `../../lib/codemirror` doesn't point to anything, so browserify fails saying it can't find `../../lib/codemirror`.

Since we're in a Common JS environment why not replace that line with: 
```
mod(require("codemirror"), require("codemirror/addon/fold/foldcode"));
```

I did this change manually and was able to get the picker to work that way.

I'm guessing a similar issue occurs in AMD?

If I missed something obvious and I'm doing it all wrong please let me know.

Apart from that issue I'm really grateful for this slick color picker! 👍

**Comment by easylogic** [comment]
@teleclimber 

v1.0.7 is released.  

It is support right require method  for nodejs, browserify, requirejs

**Comment by teleclimber** [comment]
Fantastic, thanks.

One further comment about using it with Browserify is that you have to include the addon like this:

```
require( 'codemirror-colorpicker/addon/colorpicker/colorpicker.js' );
require( 'codemirror-colorpicker/addon/colorpicker/colorview.js' );
```

At least that's the only way I could get it to work. Maybe it could be made easier, or it could be made explicit in the Readme that this is how you are supposed to `require` it.

(Note this leaves the question of how to include the CSS in the packaged application open-ended. I'm looking for a clean solution myself.)

**Comment by easylogic** [comment]
@teleclimber   

I updated README.md.

If you need anything, please tell me again.

Thanks for comment.
