### ISSUE TITLE
Is there any hotkey to show the popup widget?

### ISSUE THREAD

**Issue by 892768447** [easylogic/codemirror-colorpicker#6]
hello! Is there any hotkey to show the popup widget?
For Example:
when I write color: （here want hotkey to popup color picker）
how can i do this ?

**Comment by easylogic** [comment]
@892768447 

v1.0.7 is released. 

It is support popup color picker.

see readme for popup color picker. 

 https://github.com/easylogic/codemirror-colorpicker#support-short-cut-for-popup-color-picker
