### ISSUE TITLE
Chrome: If page body is scrolled (not codemirror), then colorpicker drag/selection goes wrong

### ISSUE THREAD

**Issue by webextensions** [easylogic/codemirror-colorpicker#8]
**Affected browser:** Google Chrome
**Works fine on:** Mozilla Firefox

**Steps to reproduce:**
- In Chrome, go to https://store.jui.io/v2/code/58930a1a94976c9b562541a6/sample/colorpicker.html
- You would see the color picker demo loaded
- Reduce the height of the browser window (for example 225px), so that the page body also gets a scrollbar
- Scroll down a little through the page body's scroll bar
- Select any color to open the color picker
- Now try to select/drag inside the color picker
- We can see that the color picker is missing the color by as many pixels as we scrolled in the body

**Where the issue lies:**
At line 581 in https://github.com/easylogic/codemirror-colorpicker/blob/master/addon/colorpicker/colorpicker.js#L581 we use:
```
var x = e.clientX - offset.left;
var y = e.clientY - offset.top;
```

Now, if we change it to:
```
var x = e.pageX - offset.left;
var y = e.pageY - offset.top;
```
**It would start working fine in Chrome but start showing up the same issue in Firefox.**

I'm not sure if it should be fixed using browser detection or some other better fix.

**Comment by easylogic** [comment]
@webextensions 

I confirmed what you said. 
I'll let you know when it's fixed.

**Comment by webextensions** [comment]
It works well now ... thanks :-)
